basePath: /api
definitions:
  model.UserResponse:
    properties:
      created_at:
        example: "2024-01-01T00:00:00Z"
        type: string
      email:
        example: lQwLd@example.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: John Doe
        type: string
      updated_at:
        example: "2024-01-01T00:00:00Z"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample api.
  title: Go-Clean Example API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: List User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponse'
      summary: List User
      tags:
      - User
swagger: "2.0"
